### ISSUE TITLE
Needs to load Multiverse first on server start, otherwise signs in unloaded worlds will not work without /ss reload

### ISSUE THREAD

**Issue by tejasxo** [MylesMor/SudoSigns#2]

**Comment by MylesMor** [comment]
Hey, thanks for your issue report. I didn't think to test with Multiverse which wasn't great in hindsight, sorry about that. Should be a simple fix, so I'll try and get it done today.

**Comment by MylesMor** [comment]
This should be fixed now as of version `1.0.1` as Multiverse will always load before SudoSigns if present. Your issue with Multiverse does also bring up a good point, unfortunately, if a world with a SudoSign is unloaded, it will say it's invalid in a `/ss reload` until the world is loaded again at which point you'll need to do `/ss reload` again... I'll try and think of ways to fix this but I'm not 100% sure yet, but that's another issue. Let me know if you have any other problems!
